language: cpp
sudo: false

compiler:
  - gcc
#  - clang

addons:
  # The following updates are needed for Travis VM running Ubuntu 12.04 and should be removed when Travis updates their OS
  # update gcc for C++11 support
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
      - george-edison55-precise-backports
    packages:
      - gcc-6
      - g++-6
      - libboost1.55-all-dev
      - cmake
      - cmake-data
      - doxygen
      - graphviz
      - build-essential
      - git
      - pkg-config
      - libfreetype6-dev
      - libfreeimage-dev
      - libzzip-dev
      - libois-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libopenal-dev
      - libx11-dev
      - libxt-dev
      - libxaw7-dev
      - libxrandr-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - libgtk2.0-dev
      - libwxgtk2.8-dev


before_install:
  # show some information about the build host
  - cat /proc/cpuinfo | grep -m1 "model name"  # CPU model
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi

install:
  - export DEPS_BUILD_DIR=$(pwd)/deps-build
  - export DEPS_INSTALL_DIR=$(pwd)/deps-install
  - export PKG_CONFIG_PATH=$DEPS_INSTALL_DIR/lib/pkgconfig
  - bash ./tools/travis/linux/dependencies.sh
script:
  - bash ./tools/travis/linux/build.sh

after_success:
  - bash ./tools/travis/linux/deploy_docs.sh


notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.org#rigsofrods-dev"
    use_notice: true

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cc9257d43908894e2e27
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
